---
- name: assert | Test if logstash_type is set correctly
  ansible.builtin.assert:
    quiet: true
    that:
      - logstash_type is defined
      - logstash_type is string
      - logstash_type in [ "enterprise", "oss" ]
